---
- name: Install system nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: setup nginx

# setup our configs for each host (we don't want to 
# overwrite certbot's changes, so if it already exists,
# don't copy!)

- name: Install nginx config for {{ domain }}
  template:
    src: templates/site.conf
    dest: /etc/nginx/conf.d/{{ domain }}.conf
    force: no
  notify: setup nginx

- name: Install nginx config for git.{{ domain }}
  template:
    src: templates/gitea.conf
    dest: /etc/nginx/conf.d/git.{{ domain }}.conf
    force: no
  notify: setup nginx

- name: Uninstall nginx config for git.{{ domain }}
  file:
    path: /etc/nginx/conf.d/git.{{ domain }}.conf
    state: absent
  notify: setup nginx

- name: Install nginx config for our Hidden Service
  template:
    src: templates/tor.conf
    dest: /etc/nginx/conf.d/tor-{{ domain }}.conf

- name: Enable Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started