- src: https://github.com/roles-ansible/ansible_role_gitea.git
  scm: git
  version: v3.5.0
  name: l3d.gitea
- src: https://github.com/geerlingguy/ansible-role-nginx.git
  scm: git
  version: 3.2.0
  name: geerlingguy.nginx
- src: https://github.com/geerlingguy/ansible-role-certbot.git
  scm: git
  version: 5.1.1
  name: geerlingguy.certbot