---
- hosts: all
  become: yes
  vars_files:
    - group_vars/all.yml

  roles:
    - role: essential
    - role: firewall
    - role: git
      tags: secrets
    - role: deadswitch
      tags: secrets
    - role: blog
    - role: gitea
    - role: nginx
    - role: goaccess
    - role: tor
      tags: secrets