---
- hosts: all
  become: yes
  vars:
    - giteaPort: 3000
    - giteaUninstall: false

  vars_files:
    - group_vars/all.yml

  vars_prompt:
    - name: domain
      prompt: domain pointing to the vps
      private: no

  roles:
    - role: essential
    - role: firewall
    - role: git
    - role: deadswitch
    - role: blog
    - role: gitea
    - role: nginx
    - role: goaccess
    - role: tor