---
- hosts: all
  become: yes
  vars_files:
    - group_vars/all.yml

  vars_prompt:
    - name: domain
      prompt: domain pointing to the vps
      private: no

  roles:
    - essential
    - git
    - deadswitch
    - firewall
    - blog
    - gitea
    - nginx
    - goaccess
    - tor