---
- hosts: all
  become: yes
  vars:
    - giteaPort: 3000
    - giteaUninstall: false

  vars_files:
    - group_vars/all.yml

  roles:
    - role: essential
    - role: firewall
    - role: git
    - role: deadswitch
    - role: blog
    - role: gitea
      tags: [backup]
    - role: nginx
    - role: goaccess
    - role: tor