---
- name: Upgrade Packages
  apt:
    update_cache: yes
    upgrade: full

- name: Install required software
  package:
    name:
      - hugo
      - git
      - nginx
      - tor
      - ufw
      - fail2ban
      - goaccess
      - htop
      - zsh # :D
      - python3-certbot-nginx

# TODO: make idempotent
- name: Setup default shell (zsh)
  shell: chsh -s /usr/bin/zsh

- name: Clone Powerlevel10k theme
  git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "/root/powerlevel10k"
    depth: 1

- name: Install .zshrc
  copy:
    src: .zshrc
    dest: /root/.zshrc
    force: no