---
- name: Clone blog repository
  git:
    repo: "https://github.com/CPunch/openpunk.git"
    dest: "/var/www/{{ domain }}"

- name: Build blog
  command:
    cmd: hugo
    chdir: "/var/www/{{ domain }}"

- name: Install updateBlog script
  template:
    src: templates/blog/updateBlog
    dest: /usr/local/bin/updateBlog
    mode: u+rwx

# Rebuild blog every hour
- name: Setup blog cron job
  cron:
    name: Build blog every hour
    minute: 0
    job: /usr/local/bin/updateBlog