---
- name: Allow port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow port 80
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp

- name: Allow port 443
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp