---
- name: Setup git config
  copy:
    src: static/.gitconfig
    dest: /root/.gitconfig
    owner: root
    mode: u=rw,g=,o=

- name: Scan for SSH host keys
  command: ssh-keyscan github.com 2>/dev/null
  register: ssh_scan

- name: Update known_hosts
  copy:
    content: "{{ ssh_scan.stdout_lines|join('\n')  }}"
    dest: /root/.ssh/known_hosts
    owner: root
    mode: u=rw,g=,o=
    force: no # if we already have a known_hosts file, ignore!

- name: Install ssh priv key
  copy:
    src: secrets/id_ed25519
    dest: /root/.ssh/id_ed25519
    mode: u=rw,g=,o=

- name: Install ssh pub key
  copy:
    src: secrets/id_ed25519.pub
    dest: /root/.ssh/id_ed25519.pub