---
- name: Configure Gitea
  template:
    src: templates/gitea/app.ini
    dest: /etc/gitea/app.ini
    owner: gitea

- name: Setup Gitea database
  become: yes
  become_user: gitea
  shell: gitea migrate -c /etc/gitea/app.ini

- name: Reload Gitea
  systemd:
    name: gitea
    enabled: yes
    state: restarted