---
- name: Configure Gitea
  template:
    src: app.ini
    dest: /etc/gitea/app.ini
    owner: gitea
    force: no # we don't want to kill our existing config D:

- name: Reload Gitea
  systemd:
    name: gitea
    enabled: yes
    state: started