---
- name: "Install gitea"
  include_role:
    name: l3d.gitea
  vars:
    gitea_fqdn: 'git.{{ domain }}'
    gitea_home: '/var/lib/gitea'
    gitea_db_type: 'sqlite3'
    gitea_theme_default: 'arc-green'
    gitea_root_url: 'https://git.{{ domain }}'
    gitea_protocol: http
    gitea_http_port: "{{ giteaPort }}"
    gitea_ssh_port: 22
    gitea_start_ssh: false
    gitea_allow_only_internal_registration: true
    gitea_disable_registration: true
    gitea_require_signin: false
    gitea_lfs_server_enabled: true

- name: Backup db
  include_tasks: backup.yml
  tags:
    - never
    - backup

- name: Restore db
  include_tasks: restore.yml
  tags:
    - never
    - restore
