#!/bin/bash
cd /var/www/{{ domain }}

PUBLIC_DIR=public
TOR_DIR=tor

buildBlog () {
    hugo --cleanDestinationDir --minify -d $PUBLIC_DIR -b https://{{ domain }}
    hugo --cleanDestinationDir --minify -d $TOR_DIR -b {{ onionDomain }}
}

git fetch origin
UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")
if [ $LOCAL = $REMOTE ]; then
    # this string is hardcoded && checked by the 'Build blog' task
    # to check for changes (changed_when)
    echo "up to date"
elif [ $LOCAL = $BASE ]; then
    # there are changes to reset to so we need to rebuild
    echo "missing changes !!"
    git reset --hard origin/main
    buildBlog
fi

if [ ! -d "$PUBLIC_DIR" ] || [ ! -d "$TOR_DIR" ]; then
    # probably first time setup
    echo "missing directories !!"
    buildBlog
fi